### PR TITLE
Create a database based on a diagram

### PR DESCRIPTION
**Pull request by WilhelmK109**
### In this milestone of the project, I did the following:
- Created a file named schema_based_on_diagram.sql
- Created a clinic database based on the provided schema diagram.
- Created tables and Join tables from many-to-many relationships.
- Added Foreign Key indexes.

### CODE REVIEW

**Review by souad988 — COMMENTED** [review]
Hi @WilhelmK109  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't include commits from your partner while it is supposed to be a pair programming activity please reach out to your peer and if he doens't respond reach out to the student success team and attach a screenshot of their response in the PR summary so that the next reviewer can start reviewing your work.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by WilhelmK109** [comment]
@souad988, thank you for your comment. I am sorry that I did not attach the screenshot for the email from student success to show that I am allowed to do my projects solo. I am sharing with you a screenshot for your own information.

Screenshot (135)

**Review by Ibizugbe — COMMENTED** [review]
Hi @WilhelmK109 👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional readme file. kindly take away every statements that give your readme file that template appearance and ensure every section is completed and personalised to match this project👍🏼.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by WilhelmK109** [comment]
@Ibizugbe, thanks for your comments and suggestions. I will make the improvements required and submit for review.

**Review by DeliceLydia — APPROVED** [review]
## Hi @WilhelmK109, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- Created a table `between medical_histories` and `treatments`
- Created indexes on all FOREIGN KEYS
- Created git workflow



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by WilhelmK109** [comment]
@DeliceLydia, thank you very much.

**Pull request merged**
